version: '3.7'
services:
  mariadb:
    image: mariadb:10.4
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=test_user
      - MARIADB_PASSWORD=secretpassword
      - MARIADB_DATABASE=rumbus_mdb_test
    ports:
      - "3306:3306"
    volumes:
      - ./docker-utils/AppDBInit.sql:/docker-entrypoint-initdb.d/AppDatabase.sql

  new_rdbms:
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=test_user
      - MARIADB_PASSWORD=secretpassword
      - MARIADB_DATABASE=rumbus_mdb_test_new
    image: mariadb:10.4
    ports:
      - "3307:3306"
    volumes:
      - ./docker-utils/newAppDBInit.sql:/docker-entrypoint-initdb.d/AppDatabase.sql

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=us-east-2

  osrm-backend:
    image: osrm/osrm-backend:v5.22.0
    command: "osrm-routed --algorithm ch /data/puerto-rico-latest.osrm"
    volumes:
      - ./maps:/data
    ports:
      - "5000:5000"
  web:
    command: yarn run start
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=test
      - PORT=8081
      - db_database=rumbus_mdb_test
      - db_host=mariadb
      - db_password=secretpassword
      - db_user=test_user
      - dynamo_accessKeyID=0
      - dynamo_endpoint=http://dynamodb:8000
      - dynamo_region=us-east-2
      - dynamo_secretAccessKey=0
      - osrm_endpoint=http://osrm-backend:5000

  api_tests:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    command: yarn run test
    depends_on:
      - web
      - dynamodb
      - osrm-backend
      - mariadb
    environment:
      - db_database=rumbus_mdb_test
      - db_host=mariadb
      - db_password=secretpassword
      - db_user=test_user
      - dynamo_accessKeyID=0
      - dynamo_endpoint=http://dynamodb:8000
      - dynamo_region=us-east-2
      - dynamo_secretAccessKey=0

volumes:
  rumbus_tests:
    driver: local
